final List<Map<String, dynamic>> mock_cars = [
    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diallo',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },
    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diallo',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },
    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diakhaté',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },
    {
      'carName': 'Voiture 39XC',
      'driverName': 'Bamba Diallo',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },
    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },    {
      'carName': 'Voiture 39XC',
      'driverName': 'Alpha Diop',
      'departureTime': '09:00',
      'price': '2.000 CFA',
      'isClimatised': true,
      'seats': 4,
    },
    // Ajoutez d'autres voitures ici
  ];