// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ4CgG8rqISpzoG2O_S2QveRC0XGweCtU',
    appId: '1:923013705052:web:ed77cf05a7e9c438f2e599',
    messagingSenderId: '923013705052',
    projectId: 'defko-mfk-guinee-transport',
    authDomain: 'defko-mfk-guinee-transport.firebaseapp.com',
    storageBucket: 'defko-mfk-guinee-transport.appspot.com',
    measurementId: 'G-2CRRW20JY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfpm-qJfwpD-FnV6osSvjfGH7vT1UboQE',
    appId: '1:923013705052:android:41ff91c87bd44b3af2e599',
    messagingSenderId: '923013705052',
    projectId: 'defko-mfk-guinee-transport',
    storageBucket: 'defko-mfk-guinee-transport.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHaObzszOrQO86UEMwt7vZ_yoQmM8W6Wk',
    appId: '1:923013705052:ios:17a1601967750225f2e599',
    messagingSenderId: '923013705052',
    projectId: 'defko-mfk-guinee-transport',
    storageBucket: 'defko-mfk-guinee-transport.appspot.com',
    iosBundleId: 'com.example.mfkGuineeTransport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHaObzszOrQO86UEMwt7vZ_yoQmM8W6Wk',
    appId: '1:923013705052:ios:17a1601967750225f2e599',
    messagingSenderId: '923013705052',
    projectId: 'defko-mfk-guinee-transport',
    storageBucket: 'defko-mfk-guinee-transport.appspot.com',
    iosBundleId: 'com.example.mfkGuineeTransport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ4CgG8rqISpzoG2O_S2QveRC0XGweCtU',
    appId: '1:923013705052:web:a0359994ff3edbeef2e599',
    messagingSenderId: '923013705052',
    projectId: 'defko-mfk-guinee-transport',
    authDomain: 'defko-mfk-guinee-transport.firebaseapp.com',
    storageBucket: 'defko-mfk-guinee-transport.appspot.com',
    measurementId: 'G-WY307LECXD',
  );
}
